name: Node.js CI/CD

on:
  push:
    branches:
      -main # Trigger on pushing to the main branch

jobs:
  build:
    runs-on: ubantu-latest

steps:
  -name: Checkout repository
  uses; action/checkout@v2

  -name: Set up Node.js
  uses: actions/setup-node@v2
  with
    node-version: '14'

-name: Install dependencies
 run: npm install

-name: Run tests
run: npm test

-name: Build Docker image
run: docker build -t my-node-app

-name: Push Docker image to registry
run: docker push <my-docker-repo>/my-node-app
